# Generated by Django 4.2.5 on 2023-10-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(blank='true', max_length=50, null='true')),
                ('Cat_Desc', models.CharField(blank='true', max_length=50, null='true')),
                ('Cat_Image', models.ImageField(blank='true', null='true', upload_to='Cat_Images')),
            ],
        ),
    ]
